Spotify_V2:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      extensions:
      - httpfs
      - json
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
